esp8266:
  board: d1_mini
  framework:
    version: recommended
esphome:
  name: d1
  compile_process_limit: 1


#Boot animation
  on_boot:
    - priority: 600
      then:
        - light.turn_on:
            id: D1_Neo
            red: 50%
            green: 0%
            blue: 50%
            effect: pulse
    - priority: 400
      then:
        - light.turn_on:
            id: D1_Neo
            red: 0%
            green: 50%
            blue: 0%
    - priority: 100
      then:
        - light.turn_on: 
            id: D1_Neo
            red: 0%
            green: 0%
            blue: 50%
            effect: none
    - priority: -100
      then:
        - light.turn_on: 
            id: D1_Neo
            effect: rainbow
        - delay: 3s
        - light.turn_on: 
            id: D1_Neo
            red: 50%
            green: 50%
            blue: 50%
            effect: pulse
        - delay: 2s
        - light.turn_on: 
            brightness: 13%
            id: D1_Neo
            red: 100%
            green: 100%
            blue: 100%
            effect: none
        - delay: 1s
        - light.turn_off: 
            id: D1_Neo

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1 Fallback Hotspot"
    password: "ICncYMIBQSg7"

captive_portal:


web_server:
  port: 80
uart:
  rx_pin: D7
  baud_rate: 9600

# Declare GPS module
gps:
  latitude:
    name: "Latitude"
  longitude:
    name: "Longitude"
  altitude:
    name: "Altitude"
  satellites:
    name: "satelites"
  speed:
    name: "gps_speed"
  course:
    name: "gps_course"

# GPS as time source
time:
  - platform: gps

  - platform: homeassistant
    id: esptime

    on_time:
      - seconds: 59
        minutes: 59
        hours: 23
        then:
          - switch.toggle: restart_sw    

sensor:
  - platform: wifi_signal
    name: "D1 WiFi Signal Sensor"
    update_interval: 60s
    
#  - platform: ccs811
#    baseline: 0x6EC3 
#    #baseline: 0x23BC
##    #baseline: 0xFEBD
#    tvoc:
#      name: "CCS811 Total Volatile Organic Compound"
#    eco2:
#      name: "CCS811 eCO2 Value"
#    address: 0x5A
#    update_interval: 60s
#    temperature: bed_temp
#    humidity: bed_hum
    
  - platform: dht
    pin: D4
    temperature:
      name: "D1 Temp"
      accuracy_decimals: 1
      filters:
        - offset: -4.3
#        - delta: 0.5
    humidity:
      name: "D1 Hum"
      accuracy_decimals: 1
      filters:
        - offset: +8.5
#        - delta: 0.5
    model: DHT11
    update_interval: 15s

  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: template
    name: D1 Uptime
    id: uptime_human
    icon: mdi:clock-start
  - platform: template
    name: Duet status
    id: ds


#i2c:
#  sda: D3
#  scl: D4
  #scan: true
  
switch:

  - platform: restart
    name: "D1 restart"
    id: restart_sw

  - platform: template
    name: "trafic_light"
    optimistic: True

binary_sensor:
  - platform: gpio
    pin: D2
    name: "sesor key"
    on_press: 
      then: 
        - light.turn_on: 
            id: D1_Neo
            effect: Police
            brightness: 100%
    on_release:
      then: 
        - light.turn_off:
            id: D1_Neo
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - light.turn_on: 
            id: D1_Neo
            effect: Traffic
light:
  - platform: neopixelbus
    #type: GRB
    variant: WS2812
    pin: D3
    num_leds: 24
    name: "D1 NeoPixel Light"
    id: D1_Neo
    color_correct: [90%,90%,90%]
    default_transition_length: 1s
    effects:
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
          
      # Use default parameters:
      - random:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 24
          width: 168
      - addressable_color_wipe:
          name: Police
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 24
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 24
          add_led_interval: 5ms
      - addressable_color_wipe:
          name: Ambulance
          colors:
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 24
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 24
          add_led_interval: 15ms
      - automation:
          name: Traffic
          sequence:
            - light.turn_on:
                id: D1_Neo
                brightness: 75%
                red: 100%
                green: 0%
                blue: 0% 
            - light.addressable_set:
                id: D1_Neo
                range_from: 0
                range_to: 24
                red: 100%
                green: 0%
                blue: 0%
            - delay: !lambda "return((rand() %2 + 5)*1000);"
            - light.addressable_set:
                id: D1_Neo
                range_from: 0
                range_to: 24
                red: 100%
                green: 100%
                blue: 0%
            - delay: 1.5s
            - light.addressable_set:
                id: D1_Neo
                range_from: 0
                range_to: 24
                red: 0%
                green: 100%
                blue: 0%
            - delay: !lambda "return((rand() %2 + 10)*1000);"
            - light.addressable_set:
                id: D1_Neo
                range_from: 0
                range_to: 24
                red: 100%
                green: 100%
                blue: 0%
            - delay: 2s
  
