esp8266:
  board: d1_mini
esphome:
  name: esp_car
  friendly_name: D1 typeC


#Boot animation
  on_boot:
    - priority: 600
      then:
        - light.turn_on:
            id: D1_Neo
            red: 50%
            green: 0%
            blue: 50%
            effect: pulse
    - priority: 400
      then:
        - light.turn_on:
            id: D1_Neo
            red: 0%
            green: 50%
            blue: 0%
    - priority: 100
      then:
        - light.turn_on: 
            id: D1_Neo
            red: 0%
            green: 0%
            blue: 50%
            effect: none
    - priority: -100
      then:
        - light.turn_on: 
            id: D1_Neo
            effect: rainbow
        - delay: 3s
        - light.turn_on: 
            id: D1_Neo
            red: 50%
            green: 50%
            blue: 50%
            effect: pulse
        - light.turn_on: 
            id: grille
            red: 50%
            green: 50%
            blue: 50%
            effect: pulse
        - delay: 2s
        - light.turn_on: 
            brightness: 13%
            id: D1_Neo
            red: 100%
            green: 100%
            blue: 100%
            effect: none
        - light.turn_on: 
            brightness: 50%
            id: grille
            red: 100%
            green: 100%
            blue: 100%
            effect: none
        - delay: 1s
        - light.turn_on: 
            id: D1_Neo
            brightness: 30%
            effect: Police


logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-7Cc14E"
    password: "95V9mrvvoYAz"

captive_portal:

time:
  - platform: homeassistant
    id: esptime

    on_time:
      - seconds: 59
        minutes: 59
        hours: 23
        then:
          - switch.toggle: restart_sw   
i2c:
  sda: D1
  scl: D2
  frequency: 800kHz
#  scan: true

ads1115:
  - address: 0x48

sensor:
########### water pressure###############
#  - platform: ads1115
#    multiplexer: 'A2_A3'
#    id: ads
#    gain: 6.144
#    filters:
#      - calibrate_linear:
#        - 0 -> 0
#        - 0.034 -> 2.5
#        - 0.038 -> 3.0
#        - 0.043 -> 3.5
#        - 0.047 -> 4.0
#      - delta: 0.05
#    name: "Pressure"
#    unit_of_measurement: Bar
#    device_class: PRESSURE
#    state_class: measurement
#    update_interval: 1s
#########################################
  - platform: ads1115
    multiplexer: 'A0_GND'
    id: ads3
    gain: 6.144
    name: "D1C 3V"
    update_interval: 5s
  - platform: ads1115
    multiplexer: 'A1_GND'
    id: ads5
    gain: 6.144
    name: "D1C 5V"
    update_interval: 5s

  - platform: wifi_signal
    name: "D1 WiFi Signal Sensor"
    update_interval: 60s

  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();
  - platform: template
    device_class: "battery"
    state_class: "measurement"
    name: Batt %
    lambda:
      return ((id(ads5).state-3) /1.2 * 100.00);
    update_interval: 1s
    entity_category: diagnostic
text_sensor:
  - platform: template
    name: D1l Uptime
    id: uptime_human
    icon: mdi:clock-start

#i2c:
#  sda: D3
#  scl: D4
  #scan: true

switch:

  - platform: gpio
    pin: D0 #choose a free pin here, just to make ESPHome happy. we do not need it for anything
    name: "Buzzer"
    id: buzz
    on_turn_on:
          - rtttl.play: 'PoliceP:d=4,o=6,b=140:8e,8c,8e,8c,8e,8c,8e,8c,8e,8c,8e,8c,8e,8c,8e,8c,8e,8c,8e,8c,8e,8c,8e,8c'
          - delay: 5s
          - rtttl.play: 'PoliceSiren:d=16,o=5,b=80:g,c6,g,c6,g,c6,g,c6,g,c6,g,c6,g,c6,g,c6,g,c6,g,c6,g,c6,g,c6'

    on_turn_off:
      - rtttl.stop
  - platform: restart
    name: "D1l restart"
    id: restart_sw

  - platform: template
    name: "trafic_light"
    optimistic: True
wled:
output:
  - platform: esp8266_pwm
    pin: D5
    id: cop_light 

  - platform: esp8266_pwm
    pin: D7
    frequency: 1000 Hz
    id: buzzer_output

rtttl:
  output: buzzer_output

light:
  - platform: monochromatic
    output: cop_light
    id: cop_led
    name: cop light
    effects:
      - strobe:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 70ms
          update_interval: 70ms
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - pulse:
          name: "Asymmetrical Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
  - platform: partition
    name: "cop red"
    id: cop_red
    segments:
      - id: D1_Neo
        from: 0
        to: 4
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.1s
          update_interval: 0.1s
      - addressable_scan:
          name: scan police 
          move_interval: 70ms
          scan_width: 2
      - strobe:
          name: Strober cop
          colors:
            - state: true
              brightness: 50%
              red: 0%
              green: 0%
              blue: 100%
              duration: 100ms
            - state: false
              duration: 100ms
            - state: true
              brightness: 50%
              red: 100%
              green: 0%
              blue: 0%
              duration: 100ms
  - platform: partition
    name: "cop blue"
    id: cop_blue
    segments:
      - id: D1_Neo
        reversed: true
        from: 6
        to: 10
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.1s
          update_interval: 0.1s
      - addressable_scan:
          name: scan police 
          move_interval: 70ms
          scan_width: 2
      - strobe:
          name: Strobeb cop
          colors:
            - state: true
              brightness: 50%
              red: 100%
              green: 0%
              blue: 0%
              duration: 100ms
            - state: false
              duration: 100ms
            - state: true
              brightness: 50%
              red: 0%
              green: 0%
              blue: 100%
              duration: 100ms
  - platform: partition
    name: "grille red"
    id: griller
    segments:
      - id: grille
        from: 0
        to: 0
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.1s
          update_interval: 0.1s
      - addressable_scan:
          name: scan police 
          move_interval: 70ms
          scan_width: 1
      - strobe:
          name: Strober cop
          colors:
            - state: true
              brightness: 70%
              red: 0%
              green: 0%
              blue: 100%
              duration: 100ms
            - state: false
              duration: 100ms
            - state: true
              brightness: 70%
              red: 100%
              green: 0%
              blue: 0%
              duration: 100ms
  - platform: partition
    name: "grille blue"
    id: grilleb
    segments:
      - id: grille
        reversed: true
        from: 1
        to: 1
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.1s
          update_interval: 0.1s
      - addressable_scan:
          name: scan police 
          move_interval: 70ms
          scan_width: 1
      - strobe:
          name: Strobeb cop
          colors:
            - state: true
              brightness: 70%
              red: 100%
              green: 0%
              blue: 0%
              duration: 100ms
            - state: false
              duration: 100ms
            - state: true
              brightness: 70%
              red: 0%
              green: 0%
              blue: 100%
              duration: 100ms
  - platform: partition
    name: "cop white"
    id: cop_white
    segments:
      - id: D1_Neo
        from: 5
        to: 5
    effects:
      - strobe:
          name: Strobew cop
          colors:
            - state: true
              brightness: 50%
              red: 100%
              green: 100%
              blue: 100%
              duration: 70ms
            - state: false
              duration: 70ms
            - state: true
              red: 0%
              green: 0%
              blue: 0%
              duration: 70ms
  - platform: neopixelbus
    #type: GRB
    variant: WS2812
    pin: D6
    num_leds: 2
    name: "grille"
    id: grille
    #color_correct: [90%,90%,90%]
    default_transition_length: 1s
    effects:
      - wled:
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
          
      # Use default parameters:
      - random:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 1s
          update_interval: 5s
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.1s
          update_interval: 0.1s
      - pulse:
          name: "Slow Pulse"
          transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 50
          width: 11
      - addressable_scan:
      - addressable_scan:
          name: Scan Effect 
          move_interval: 100ms
          scan_width: 1
      - flicker:
      - flicker:
          name: Flicker Effect
          alpha: 95%
          intensity: 1.5%
      - addressable_color_wipe:
          name: Police
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 1
          add_led_interval: 20ms
      - addressable_color_wipe:
          name: Ambulance
          colors:
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 2
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 2
          add_led_interval: 20ms
      - addressable_color_wipe:
          name: red flash
          colors:
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 2
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 2
          add_led_interval: 20ms
  - platform: neopixelbus
    #type: GRB
    variant: WS2812
    pin: D3
    num_leds: 11
    name: "D1l NeoPixel Light"
    id: D1_Neo
    #color_correct: [90%,90%,90%]
    default_transition_length: 1s
    effects:
      - wled:
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
          
      # Use default parameters:
      - random:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 1s
          update_interval: 5s
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.1s
          update_interval: 0.1s
      - pulse:
          name: "Slow Pulse"
          transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 50
          width: 11
      - addressable_scan:
      - addressable_scan:
          name: Scan Effect 
          move_interval: 100ms
          scan_width: 1
      - addressable_scan:
          name: scan police 
          move_interval: 100ms
          scan_width: 2
      - flicker:
      - flicker:
          name: Flicker Effect
          alpha: 95%
          intensity: 1.5%
      - addressable_color_wipe:
          name: Police
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 11
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 11
          add_led_interval: 20ms
      - addressable_color_wipe:
          name: Ambulance
          colors:
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 11
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 11
          add_led_interval: 20ms
      - addressable_color_wipe:
          name: red flash
          colors:
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 11
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 11
          add_led_interval: 20ms
      - automation:
          name: Traffic
          sequence:
            - light.turn_on:
                id: D1_Neo
                brightness: 75%
                red: 100%
                green: 0%
                blue: 0% 
            - light.addressable_set:
                id: D1_Neo
                range_from: 0
                range_to: 11
                red: 100%
                green: 0%
                blue: 0%
            - delay: !lambda "return((rand() %2 + 5)*1000);"
            - light.addressable_set:
                id: D1_Neo
                range_from: 0
                range_to: 11
                red: 100%
                green: 100%
                blue: 0%
            - delay: 1.5s
            - light.addressable_set:
                id: D1_Neo
                range_from: 0
                range_to: 11
                red: 0%
                green: 100%
                blue: 0%
            - delay: !lambda "return((rand() %2 + 10)*1000);"
            - light.addressable_set:
                id: D1_Neo
                range_from: 0
                range_to: 11
                red: 100%
                green: 100%
                blue: 0%
            - delay: 2s
      - automation:
          name: cop lights
          sequence:
            - light.turn_on:
                brightness: 50%
                id: cop_red
                red: 100%
                green: 0%
                blue: 0%
                effect: scan police
            - light.turn_on:
                id: cop_blue
                brightness: 50%
                red: 0%
                green: 0%
                blue: 100%
                effect: scan police
            - light.turn_on:
                id: cop_white
                brightness: 30%
                effect: Strobew cop
            - light.turn_on:
                brightness: 70%
                id: griller
                red: 100%
                green: 0%
                blue: 0%
                effect: Scan Effect
            - light.turn_on:
                id: grilleb
                brightness: 70%
                red: 0%
                green: 0%
                blue: 100%
                effect: Scan Effect
            - delay: 3s
            - light.turn_on:
                id: cop_red
                effect: Strober cop
            - light.turn_on:
                id: cop_blue
                effect: Strobeb cop
            - light.turn_on:
                id: griller
                effect: Strober cop
            - light.turn_on:
                id: grilleb
                effect: Strobeb cop
            - light.turn_off:
                id: cop_white
            - delay: 3s
   
 
